#Scan the docker file for common vulnerabilities and best practices
#Uses Hadolint

name: Docker lint
on:
    workflow_dispatch:

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate Dockerfile by running hadolint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: ./Dockerfile      