#Checks for API Keys, Sensitive data, Credentials
#Uses Gitleaks

name: Secrets Scan
on:
    workflow_dispatch:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0   #Fetches the entire history to scan all commits for secrets

            - name: Run Gitleaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} #Github token for authentication provided by github actions